#!/usr/bin/env python3
"""Generate basic bitboard lookup tables for future engine migration."""

from __future__ import annotations

import argparse
import os
from typing import List


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Generate NASM bitboard lookup tables")
    p.add_argument("--output", default="src/bitboard_tables.inc", help="output include file")
    return p.parse_args()


def sq(file_idx: int, rank: int) -> int:
    return rank * 8 + file_idx


def on_board(file_idx: int, rank: int) -> bool:
    return 0 <= file_idx < 8 and 0 <= rank < 8


def bb_for_targets(start: int, deltas: List[tuple[int, int]]) -> int:
    f = start % 8
    r = start // 8
    bb = 0
    for df, dr in deltas:
        nf = f + df
        nr = r + dr
        if on_board(nf, nr):
            bb |= 1 << sq(nf, nr)
    return bb


def bb_ray(start: int, delta: tuple[int, int]) -> int:
    f = start % 8
    r = start // 8
    df, dr = delta
    bb = 0
    nf = f + df
    nr = r + dr
    while on_board(nf, nr):
        bb |= 1 << sq(nf, nr)
        nf += df
        nr += dr
    return bb


def emit_table(name: str, values: List[int]) -> str:
    lines = [f"{name}:"]
    for v in values:
        lines.append(f"    dq 0x{v:016x}")
    return "\n".join(lines)


def main() -> int:
    args = parse_args()

    knight_deltas = [
        (-2, -1), (-2, 1),
        (-1, -2), (-1, 2),
        (1, -2), (1, 2),
        (2, -1), (2, 1),
    ]
    king_deltas = [
        (-1, -1), (-1, 0), (-1, 1),
        (0, -1),           (0, 1),
        (1, -1),  (1, 0),  (1, 1),
    ]
    rays = {
        "bb_ray_n": (0, 1),
        "bb_ray_s": (0, -1),
        "bb_ray_e": (1, 0),
        "bb_ray_w": (-1, 0),
        "bb_ray_ne": (1, 1),
        "bb_ray_nw": (-1, 1),
        "bb_ray_se": (1, -1),
        "bb_ray_sw": (-1, -1),
    }

    knight = [bb_for_targets(i, knight_deltas) for i in range(64)]
    king = [bb_for_targets(i, king_deltas) for i in range(64)]

    text = []
    text.append("; Auto-generated by tests/tuning/generate_bitboard_tables.py")
    text.append("; Do not edit manually.")
    text.append("")
    text.append("section .rodata")
    text.append(emit_table("bb_knight_attacks", knight))
    text.append("")
    text.append(emit_table("bb_king_attacks", king))
    text.append("")
    for name, delta in rays.items():
        values = [bb_ray(i, delta) for i in range(64)]
        text.append(emit_table(name, values))
        text.append("")

    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        f.write("\n".join(text))

    print(f"generated: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
